### ISSUE TITLE
Named parameter is not correctly parsed when it uses former param

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#164]
Example:
```yaml
params: ONE=1 TWO=`expr 1 + ${ONE}`
steps:
  command: echo $ONE $TWO
```
