### ISSUE TITLE
Why is dagu reading irrelevant YAML files?

### ISSUE THREAD

**Issue by kseistrup** [yohamta/dagu#199]
I started `dagu` with `dagu server` in my homedir [on Linux], and now the webui asks me to check three “errors below”. Those “errors” are — according to `dagu` — incompatible YAML errors, but why on Earth is `dagu` reading YAML files that has got nothing to do with `dagu`? Is it simply scanning the homedir and reading each and every YAML file it can find?

**Comment by yohamta** [comment]
Dagu read YAML files placed in the current directory unless you set the `dags` config in the admin config file.
Please create `~/.dagu/admin.yaml`.

```yaml
host: <hostname for web UI address>                          # default value is 127.0.0.1
port: <port number for web UI address>                       # default value is 8000
dags: <the location of DAG configuration files>              # default value is current working directory
```

I suppose the default DAG directory should not be current directory but other directory so yaml files are not mixed up, for example `~/.dagu/dags`. We'll fix this soon.
