### ISSUE TITLE
Draft: Add `start:` and `stop:` fields for running/stopping child DAGs on the same directory

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#217]
It should have a method to call/stop other DAG.
Currently DAG can call other DAG by using the `dagu start` command but it should be suppoerted natively.

Example:

```yaml
steps:
  - name: start a child DAG
    start: child_DAG
  - name: wait 30min
    command: sleep 1800
  - name: stop a child DAG
    stop: child_DAG
    depends:
      - wait 30min
```
