### ISSUE TITLE
when output value is json or contains double-quotes, got wrong value in next step

### ISSUE THREAD

**Issue by lixiv** [yohamta/dagu#231]
examples:
```
steps:
  - name: "first"
    command: "echo {\"key\":\"value\"}"
    output: JSON
  - name: "second"
    command: "echo $JSON"
    depends:
      - first
```
