### ISSUE TITLE
When a quoted argument contains spaces the parameters are not passed to the command correctly

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#239]
Example:
```yaml
env:
  - FILE_NAME: /tmp/hello-world.txt
steps:
  - name: step1
    command: echo "hello world"
    stdout: $FILE_NAME
  - name: step2
    command: sed -i 's/hello world/HELLO WORLD/g' $FILE_NAME
    depends:
      - step1
  - name: step3
    command: cat $FILE_NAME
    depends:
      - step2
```
