### ISSUE TITLE
`\t` argument will be passed as `t` in step command

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#262]
**Minimal reproducible example DAG**
```yaml
steps:
  - name: 1
    command: echo "\t"
```
