### ISSUE TITLE
Arguments after semicolon (`;`) will not be passed to the program when not quoted

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#279]
**Minimal reproducible example DAG**
```yaml
steps:
  step:
    - name: step 1
      command: echo HELLO; WORLD
```

**Expected behavior**
expected: `HELLO WORLD`
actual: `HELLO`

**Comment by Arvintian** [comment]
Like shell's special char hint this issue, '&' don't work so.
If the arguments are enclosed with double quotes or single quotes, this issue does not happen.
```
steps:
  - name: step1
    executor: http
    command: put 'http://127.0.0.1:7000/api?var1=$1&var2=$2'
    script: |
      {"timeout":10,"headers":{"Content-Type":"application/json"},"body":""}
```
I think the behavior produce by shellwords. Like shellworlds pasre string be quoted as raw-string.
