### ISSUE TITLE
Small Issue with `Params` in Spec View 

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#280]
When there's a space in the `Param` value between named parameters, the space would would not be displayed in the spec view.

ex:
```yaml
params: "P1=foo P2=bar"
steps:
  - name: step1
    command: echo hello
```
