### ISSUE TITLE
Running containers instead of bare commands

### ISSUE THREAD

**Issue by ChristianKniep** [yohamta/dagu#298]
Wondering if you ever thought about using a container for execution instead of a process..

Should be rather simple to implement.

**Comment by yohamta** [comment]
Thanks for raising the issue!
We will prepare containers and DockerCompose setup later. As of now, there's only a Dockerfile for `dagu server` [here](https://github.com/yohamta/dagu/blob/main/Dockerfile).

**Comment by ChristianKniep** [comment]
Hey, my goal is not to run the server in a container (even though that is certainly a good thing to do anyways), but instead run the tasks containerized. Like
```
steps:
  - name: step 1
    container: alpine:3.16.2
    command: echo hello
  - name: step 2
    container: pandoc/core 
    command: README.md -o outfile.pdf
    depends:
      - step 1
```
That way you abstract away the need to have all the tools installed (in a specific version).

**Comment by yohamta** [comment]
Ah, sorry for my misunderstanding. Being able to run containers natively is a great idea. Let's look into how to implement such a feature.

**Comment by ChristianKniep** [comment]
I reckon it should be rather simple to create a `ContainerExecution.go` extension.
https://github.com/yohamta/dagu/blob/main/internal/executor/command.go

I'll try to give it a shot some time. Need to prep for a workshop tho. :)

**Comment by yohamta** [comment]
That would be a huge help! Thank you very much :)

**Comment by Arvintian** [comment]
I think we can just implement the executor interface https://github.com/yohamta/dagu/blob/main/internal/executor/executor.go#L12. 
By the way, i think we can support docker container or kubernetes pod executor (confilct with kubernetes's cronjob?).
About more the executor may be need settings info. We should open a field to config executor?

**Comment by yohamta** [comment]
Thank you! I agree with you. I am not sure but think we will need to add some DAG fields to config executor for docker / k8s.

**Comment by yohamta** [comment]
Let's extend the exectutor interface and then add a container executor.

**Comment by yohamta** [comment]
Added `executorConfig` field in `Step` struct in #321 PR.
It turns out we didn't have to update the `Executor` interface thanks to the great design done by @Arvintian 
Now I think we can add any executor as well as docker container executor, by adding a new Executor here: https://github.com/yohamta/dagu/blob/main/internal/executor/http.go#L96

**Comment by yohamta** [comment]
I think we can use DockerEngine's Go SDK: https://docs.docker.com/engine/api/sdk/

**Comment by yohamta** [comment]
@ChristianKniep Sorry to keep you waiting :) Are you still interested in making a simple `ContainerExecution.go` extension?

**Comment by ChristianKniep** [comment]
@yohamta I am on the road attending a workshop, so I was busy and will be back next week. I still super interested in a container executor. If you are faster than me - I would not mind.

**Comment by ChristianKniep** [comment]
If you have some boilerplate for me to fill out I can add the container logic.

**Comment by yohamta** [comment]
@ChristianKniep That's great. No need to rush, thank you so much. Good luck with the workshop 👍
Will prepare the boilerplate later :)

**Comment by yohamta** [comment]
@ChristianKniep Here is the [boilerplate](https://github.com/yohamta/dagu/blob/main/internal/executor/docker.go) and an [Example DAG](https://github.com/yohamta/dagu/blob/main/examples/docker-container.yaml).
You can run the example DAG with this command:
```sh
go run ./cmd start ./examples/docker-container.yaml
```
Thanks!

**Comment by ChristianKniep** [comment]
Cool, some questions.
- Do you expect the process to have access to files? Like: A container instance might create a volume for each step and allow those to be mounted by subsequent steps to access data.
- all parents of a step needs to finish before the next step is allowed to start, right?

**Comment by yohamta** [comment]
> Do you expect the process to have access to files? Like: A container instance might create a volume for each step and allow those to be mounted by subsequent steps to access data.

Personally, I think it would be better to leave that to the user's configuration. I thought it would be better to be able to set this Bind argument in the DAG's `executorConfig`. If the user wants to mount it on a local volume, I think it could be configured as follows.
```yaml
steps:
  - name: step1
    executor: docker
    executorConfig:
      - image: node
        binds:
          - "/localPath:/pathInDocker"
    command: npm install
```
Then the DockerConfig struct in the boilerplate I prepared would need to be modified.

> all parents of a step needs to finish before the next step is allowed to start, right?

I thought it depends on the setting of the `depends` key in the DAG, if depends is set to the name of the parent step, then that step will complete first. Does that answer your question?
```yaml
steps:
  - name: parent
    executor: docker
    executorConfig:
      - image: node
        binds:
          - "/localPath:/pathInDocker"
    command: npm install
  - name: child
    executor: docker
    executorConfig:
      - image: node
        binds:
          - "/localPath:/pathInDocker"
    command: npm start
    depends:
       - parent
```
The DAG definition above looks redundant, but I think that can be improved later by adding a some generic template feature or something where user can reuse settings for the container steps. What do you think?

**Comment by ChristianKniep** [comment]
ok, makes sense... Lemme give it more thought in the next couple of days.

**Comment by yohamta** [comment]
no problem :)

**Comment by yohamta** [comment]
I just thought that the executor name & executorConfig should be in a same struct.

```go
package dag
type Executor struct {
  name: string
  config: map[string]interface{}
}
```

DAG definition:
```yaml
steps:
  - name: S1
    executor:
     name: docker
     config:
       image: node
       binds:
         - "/localPath:/pathInDocker"
    command: npm install
```

I will refactor this separately once the docker implementation finished.
