### ISSUE TITLE
Allow `start` and `stop` time definition for `schedule` field

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#303]
Allow defining start and end times for long-running processes.
When the end time is reached, send a signal to stop the processes.

Example:
```yaml
schedule:
  start: "0 8 * * *"
  stop: "0 20 * * *"

# some long running processes
steps:
  - name: step1
    command: python start.py
```

- [ ] Modify the parsing logic for `schedule` field
- [ ] Add the ability for the `scheduler` to send signals to the running processes at the `stop` time.
