### ISSUE TITLE
Add `restart` subcommand

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#314]
The user should be able to restart a DAG execution. The restart command stops the current execution and starts the DAG after a certain pause time for cleanup. If the DAG is not running, it just starts the DAG.

```sh
dagu restart ./dags/task.yaml
```

The cleanup time for `restart` should be configured in the DAG definition. The default value is 0.
```yaml
RestartWaitSec: 30
```

**Comment by yohamta** [comment]
Need to add this to schedule field also:
```yaml
schedule:
  start: "0 8 * * *"
  restart: "0 12 * * *"
  stop: "0 23 * * *"
```
