### ISSUE TITLE
SSH executor

### ISSUE THREAD

**Issue by fishnux** [yohamta/dagu#316]
Similar to issue https://github.com/yohamta/dagu/issues/298 for creating a container executor, I propose the creation of a SSH executor to run tasks on remote servers

Current workaround is to execute ssh command

**Comment by yohamta** [comment]
Thanks for the suggestion! That sounds like a useful idea.
I'm trying to figure out how to make it a generic feature that would work for a variety of Executors, including SSH, Docker, and HTTP hooks.
A naive way might be something like this. However, this approach might seem a bit complicated with more fields required for various Executors. Any ideas?
```yaml
steps:
  - name: step1
     executor: ssh
     command: do something
  - name: step2
     executor: docker
     container: node:latest
     command: node app.js
     depends:
        - step1
````

Translated with www.DeepL.com/Translator (free version)

**Comment by yohamta** [comment]
I think one way might be to extend the [Executor](https://github.com/yohamta/dagu/blob/main/internal/executor/executor.go) interface.

```go
package dag
type DAG struct {
  // ...
  Executor: string
  ExecutorConfig: map[string]interface{}
}

package executor
type Executor interface {
  SetStdout(out io.Writer)
  SetStderr(out io.Writer)
  Kill(sig os.Signal) error
  Run() error
  // For loading Executor specific config
  LoadConfig(dag *dag.DAG, execConfig *map[string]interface{}) error
}
````

**Comment by fishnux** [comment]
Your proposed solution sounds nice! 👍 

On a side-note, food for thought: what if I want to run a Docker container (executor) through SSH? 😮

**Comment by yohamta** [comment]
Thanks!
In that case, I think you might want to set `DOCKER_HOST` environ variable to run docker on remote server via ssh :)
Like this (not sure though).
```yaml
steps:
  - name: step1
    executor: docker
    env:
     - DOCKER_HOST: ssh://docker-user@host1.example.com
    executorConfig:
      context: /home/app/Dockerfile
    command: node app.js
```
Let's see if it would work.
