### ISSUE TITLE
Add ExecutorConfig field to Step definition

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#321]
Update Executor's interface to provide the unified way to configure executors in DAG specs.
~~- [ ] Extend the [Executor](https://github.com/yohamta/dagu/blob/main/internal/executor/executor.go) interface~~
- [ ] Add `executor` and `executorConfig` field to DAG spec

See also: #298 #316 

Update image:
```go
package dag
type Step struct {
  // ...
  Executor: string
  ExecutorConfig: map[string]interface{}
}

package executor
type Executor interface {
  SetStdout(out io.Writer)
  SetStderr(out io.Writer)
  Kill(sig os.Signal) error
  Run() error
}
````

DAG spec example:
```yaml
steps:
  - name: step1
    executor: ssh
    executorConfig:
      host: xxx
      port: 22
      key: /home/dagu/.ssh/xxx
    command: java /home/app/app.jar
  - name: step2
    executor: docker
    executorConfig:
      context: /home/app/Dockerfile
    command: node app.js
    depends:
       - step1
````
