### ISSUE TITLE
signalOnStop broken (tested on web UI)

### ISSUE THREAD

**Issue by fishnux** [yohamta/dagu#328]
Hi,

signalOnStop is being ignored when stopping through the Web UI. Haven't tested other methods to stop the DAG

```
steps:
  - name: step1
    command: bash
    script: |
      for s in {1..64}; do trap "echo trap $s" $s; done
      sleep 60
    signalOnStop: "SIGINT"
```
Stop the DAG shortly after starting
Log:
```
Terminated
trap 15
trap 17
```
15 is SIGTERM
17 is SIGCHLD
