### ISSUE TITLE
Consider new syntax for dependency definitons

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#335]
The current way of defining dependency is a bit cumbersome when updating. It is nice to have a convenient way of defining dependency with a simple syntax.

Example1:
```yaml
dependency: S1 > (S2, S3)
steps:
  - name: S1
    command: "echo S1"
  - name: S2
    command: "echo S3"
  - name: S3
    command: "echo S3"
```

Example2:
```yaml
dependency:
  - S1 > S2
  - S1 > S3
steps:
  - name: S1
    command: "echo S1"
  - name: S2
    command: "echo S3"
  - name: S3
    command: "echo S3"
```
