### ISSUE TITLE
Add auth to smtp mailer

### ISSUE THREAD

**Issue by triole** [yohamta/dagu#338]
**Is your feature request related to a problem? Please describe.**
I'd like to send mails using an smtp mailer that requires authentication. Therefore it would be nice to be able to provide username and password to a working login method.

**Describe the solution you'd like**
The golang smtp package has an auth method. Unfortunaltely I was not able to build dagu because there is something wrong with yarn.  It told me that there are scenarios missing. Otherwise I'd tried to implement the smtp authentication myself. I guess I'd be something like this

```
auth := smtp.PlainAuth("", from, password, host)
err := smtp.SendMail(host+":"+port, auth, from, toList, body)
```

**Comment by yohamta** [comment]
Thanks for submitting the request. I will take a look.

**Comment by yohamta** [comment]
@triole Now the STMP configuration with username and password is available in v1.8.8.

Example DAG:
```yaml
steps:
  - name: S1
    command: echo mail test

# Eamil notification settings
mailOn:
  failure: true
  success: true

# SMTP server settings
smtp:
  host: "smtp.foo.bar"
  port: "587"
  username: "<username>"
  password: "<password>"

# Error mail configuration
errorMail:
  from: "foo@bar.com"
  to: "foo@bar.com"
  prefix: "[Error]"

# Info mail configuration
infoMail:
  from: "foo@bar.com"
  to: "foo@bar.com"
  prefix: "[Info]"
```
