### ISSUE TITLE
Countdown for scheduled job display (cosmetics)

### ISSUE THREAD

**Issue by kwmiebach** [yohamta/dagu#385]
I have a schedule set like this:

```
schedule: "*/5 0-6 * * *"
steps:
  - name: do-something
    command: /bin/bash -c "do something ..."
```

The display of the remaining time till the next run looks inverted, or is this intentional?

In fact 4 hours 21 minutes is  the correct value

![image](https://user-images.githubusercontent.com/6737928/220726523-0e04bcba-33b9-4041-ad16-3a9e4709ec24.png)
