### ISSUE TITLE
http executor not support json format http body

### ISSUE THREAD

**Issue by bbqi** [yohamta/dagu#392]
```
steps:
  - name: send POST request
    executor: http
    command: POST https://foo.bar.com
    script: |
      {
        "timeout": 10,
        "headers": {
          "Authorization": "Bearer $TOKEN"
        },
        "query": {
          "key": "value"
        },
        "body": {
           "key": "value"
        }
      }   
```
ERROR :  json: cannot unmarshal object into Go struct field HTTPConfig.body of type string

**Comment by Arvintian** [comment]
You need to manually encode the data into a JSON string.

**Comment by Arvintian** [comment]
http executor body field is string to send any data.

**Comment by yohamta** [comment]
Yeah, that's true. Maybe we might want to add `body` key to HTTP executor so that we can pass unescaped JSON string. I will do it soon.

**Comment by bbqi** [comment]
USE cURL！

The output of the http executor is mixed with the http response header and the result, which makes the next step of analysis more difficult. For example, it is necessary to judge the request status based on the status code and analyze the response content

```
steps:
  - name:  get_http_respons
    # -s slient mode
    command:  bash
    script: |
       curl -s http://foo.bar.com
    output: RESULT
  - name:  get_http_header
    # -I only header
    command:  bash
    script: |
       curl -s -I http://foo.bar.com
    output: HEADER
```
