### ISSUE TITLE
Mail Executor

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#402]
I would like to use the Mail executor to enable sending arbitrary emails during a workflow.

```yaml
steps:
  - name: send email
    executor:
      type: mail
      config:
        to: <to address>
        from: <from address>
        subject: <subject>
        message: <message>
 ```
