### ISSUE TITLE
`silent` option for `http` executor

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#403]
- I would like to specify the body in the `command` field to avoid the need for escaping when embedding it in the script  field.
- I want to set the `silent` option so that I can use the command similar to the `curl` command.

```yaml
steps:
  - name: send request
    executor:
      type: http
      config:
        body:  $BODY,
        timeout: 10,
        silent: true,
        headers:
          Authorization: "Bearer $TOKEN"
        query:
          key: value
    command: POST https://foo.bar.com
    output: OUTPUT_JSON
```
